version: '2'
services:
  neoj:
    image: neo4j:latest
    container_name: neo4j-paprika
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
  web:
    ports:
      - "4567:4567"
    image: paprika-web:latest
    container_name: web-paprika
    command: java -jar Paprika-web.jar -d
    volumes:
       - .:/dock
       - /var/run/docker.sock:/var/run/docker.sock
    links:
      - neoj
    depends_on:
      - neoj
  analyse:
    image: paprika-analyze:latest
    command: java -jar Paprika-analyze.jar com.lucasdnd.bitclock16_1.apk 579735 g@p Example_1 23 51
    links:
      - neoj
    depends_on:
      - neoj
    volumes_from:
      - web
    ports:
      - "4568:4568"
