FROM openjdk:8-jre-alpine

MAINTAINER Guillaume Willefert
WORKDIR /dock
ADD Paprika-Tandoori.jar /dock
ADD CodeSmellsAnnotations.jar /dock
ADD android-platforms /dock/android-platforms
ADD input /dock/input
ADD output /dock/output